### ISSUE TITLE
EVERYTHING BREAKS ON MOBILE (Chrome Mobile)

### ISSUE THREAD

**Issue by theandrewchan** [codebase-berkeley/codebase-website#11]
- [x] Menu doesn't work
- [x] Landing page hero has gap on right
- [x] Footer has gap on right
- [x] Footer tries to squeeze everything in horizontally, looks like ass
- [x] Landing page photos get cut off horizontally
- [x] Sutro's logo disappears in the portfolio section for some reason
- [x] And a bunch of other stuff

**Comment by theandrewchan** [comment]
Checkout https://developers.google.com/web/tools/chrome-devtools/remote-debugging/ for a cool guide on how to test+inspect the site on chrome mobile while serving from your local machine

**Comment by theandrewchan** [comment]
@ssss1029  changes fixed the gap on the right and the menu :grin: :+1:

**Comment by ssss1029** [comment]
More stuff to fix: http://imgur.com/a/gJwAI

**Comment by ssss1029** [comment]
+ there are issues with the onto, crowdbotics, etc pages on mobile

**Comment by ssss1029** [comment]
Everything should be fixed @theandrewchan 😄
