### ISSUE TITLE
landing page content and styling

### ISSUE THREAD

**Issue by cindyjyuan** [codebase-berkeley/codebase-website#39]

**Comment by OldGuo** [comment]
Totally don't remember what this one was asking for, but can you do the styling for like this part?
![image](https://user-images.githubusercontent.com/2722397/43988658-8a03fcfe-9cef-11e8-912b-68f3e67e4ef2.png)
![image](https://user-images.githubusercontent.com/2722397/43988662-9376d9aa-9cef-11e8-91ac-27e878a96ceb.png)
