### ISSUE TITLE
home page get involved section

### ISSUE THREAD

**Issue by cindyjyuan** [codebase-berkeley/codebase-website#42]
under "for students" learn more goes to about page
under "for companies" learn more goes to projects (?) page

**Comment by edricx** [comment]
Section looks like this now. Need to fix image size (my css doesn't seem to be applying properly...) and the "For companies" button links to the about page for now while the services page is sorted out.

![image](https://user-images.githubusercontent.com/13011705/44007907-a7309eb4-9e51-11e8-9851-926b842ab869.png)

**Comment by cindyjyuan** [comment]
looks good! we can have the companies button link to the projects page

**Comment by edricx** [comment]
Companies now links to the project page. Something weird still going on on my end with hugo not showing new CSS rules that I add so I can't see my images being resized. I added this to gridCards.css anyways so hopefully the resized images show up on your end.

`.involved-section .card-img-top {
  max-width: 150px;
}`

**Comment by cindyjyuan** [comment]
The icon sizing looks good on my end!
