### ISSUE TITLE
about page alumni placement section where we f l e x

### ISSUE THREAD

**Issue by cindyjyuan** [codebase-berkeley/codebase-website#45]

**Comment by trev4ev** [comment]
Will the company logos be put together as a single image or we will have a file for each logo? @cindyjyuan @OldGuo

**Comment by cindyjyuan** [comment]
That's a good point, I'll upload a single image

**Comment by OldGuo** [comment]
I think we should do individual files? That way it's really easy to add more

**Comment by cindyjyuan** [comment]
Uploaded individual company logos here: https://drive.google.com/drive/u/0/folders/116QJOpRgAAV5PouRf3xUFBRYlIHofyZM

**Comment by cindyjyuan** [comment]
![screen shot 2018-08-14 at 6 04 02 pm](https://user-images.githubusercontent.com/18675255/44126324-75a86132-9fec-11e8-9220-036f09969282.png)
