### ISSUE TITLE
Fancy CSS transitions on various things

### ISSUE THREAD

**Issue by OldGuo** [codebase-berkeley/codebase-website#58]
It's all about these smooth transitions/highlights/etc. to make a website look really great (not super critical if we don't get to this)

**Comment by cindyjyuan** [comment]
e.g. have elements on the page load at different times, project cards zoom on hover, change button opacity on hover, etc.

**Comment by cindyjyuan** [comment]
other ideas: have elements (e.g. cards?) load on scroll,

**Comment by cindyjyuan** [comment]
Think we have enough transitions for now :)
