### ISSUE TITLE
Add project structure section

### ISSUE THREAD

**Issue by cindyjyuan** [codebase-berkeley/codebase-website#71]
![screen shot 2018-08-15 at 1 28 07 pm](https://user-images.githubusercontent.com/18675255/44171460-1c474380-a08f-11e8-97eb-839e724798af.png)

**Comment by OldGuo** [comment]
Awesome that we're adding this section! I'm a little bit concerned about how similar this looks to Blueprint's "Apply" page though 

![image](https://user-images.githubusercontent.com/2722397/44171598-73e5af00-a08f-11e8-82be-456aa5f997d0.png)

**Comment by cindyjyuan** [comment]
![screen shot 2018-08-16 at 11 45 24 am](https://user-images.githubusercontent.com/18675255/44228339-ef0b9b80-a149-11e8-9413-de7e3250ce9f.png)
alternative design

**Comment by OldGuo** [comment]
I just tried to do this its really hard HAHA
