### ISSUE TITLE
Make everything mobile-friendly!!!

### ISSUE THREAD

**Issue by cindyjyuan** [codebase-berkeley/codebase-website#83]

**Comment by cindyjyuan** [comment]
Primarily these 2 sections on the home and projects page:

![screen shot 2018-08-19 at 4 15 57 pm](https://user-images.githubusercontent.com/18675255/44314240-4cfae600-a3cb-11e8-88f9-dece1b842640.png)
![screen shot 2018-08-19 at 4 15 33 pm](https://user-images.githubusercontent.com/18675255/44314241-4cfae600-a3cb-11e8-9341-5336dda91f35.png)

**Comment by cindyjyuan** [comment]
last thing is making hamburger icon show up on mobile @OldGuo any clue why this isn't working?

**Comment by OldGuo** [comment]
After some digging, the hamburger icon is actually this image that bootstrap magic places into the `navbar-toggler-icon` class depending on whether the navbar is `navbar-light` or `navbar-dark`. Since ours was neigher, our good hamburger friend disappeared

**Comment by OldGuo** [comment]
Should we close this @trev4ev @cindyjyuan?

**Comment by cindyjyuan** [comment]
Yup yup! Thanks a lot @trev4ev!!!
