### ISSUE TITLE
Make a finalized, public recruiting calendar

### ISSUE THREAD

**Issue by OldGuo** [codebase-berkeley/codebase-website#87]
I currently put a dummy `iframe` here for testing, but we should but a *real* public calendar on here with all the correct dates

@c0dyzeng could you make a public version with all the recruitment events and link it?

![image](https://user-images.githubusercontent.com/2722397/44385041-1dcf9c00-a4d3-11e8-8905-0b5a2825e2bb.png)

**Comment by c0dyzeng** [comment]
Yeah sure hahaha

**Comment by c0dyzeng** [comment]
I feel like for recruiting timeline, we should still do an actual timeline, as it's more clear what the events are.

**Comment by c0dyzeng** [comment]
![image](https://user-images.githubusercontent.com/19477036/44415856-42089880-a526-11e8-8ee4-e567e2d26be0.png)

**Comment by c0dyzeng** [comment]
![image](https://user-images.githubusercontent.com/19477036/44415871-4e8cf100-a526-11e8-8bf0-76230d96cb72.png)

**Comment by c0dyzeng** [comment]
just a lot easier to see what's happening at a glance

**Comment by OldGuo** [comment]
Damn yeah I tried to do the dots thing but it wasn't super straightforward to implement :/ I really like that second screenshot though! Maybe simple is just better @cindyjyuan?

Alternatively we could reuse the cards from the projectTimeline partial

**Comment by cindyjyuan** [comment]
something super jank is we can just add a screenshot of the timeline i made for the flyer/cover photo

**Comment by cindyjyuan** [comment]
done
